spring:
  application:
    name: ems-server
  main:
    allow-circular-references: true
  profiles:
    active: dev
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath*:mapper/**/*.xml
