spring:
  datasource:
    url: jdbc:mysql://{$IP_ADDR}:{$PORT}/{DATABASE}?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: {$PASSWORD}
    druid:
      max-active: 50
  elasticsearch:
    uris: http://{$IP_ADDR}:{$PORT}
    username: ems
    password: {$PASSWORD}
  redis:
    host: {$IP_ADDR}
    port: {$PORT}
    timeout: 50000
    password: {$PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: ems_sql_schema
    placeholder-replacement: false
    validate-on-migrate: false
    locations: classpath:migration/base,classpath:migration/release
  cache:
    redis:
      time-to-live: 3600000
      cache-null-values: true
      use-key-prefix: true
  main:
    lazy-initialization: false
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  cloud:
    nacos:
      discovery:
        register-enabled: false